# -*- coding: utf-8 -*-
"""Prototype

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j2B7LGJJtfE3_Epe3Xjs9DhHl7ITy0XC
"""

"""
Wordle Solver created by James Kirk
https://github.com/Jkirk2

"""
import time

#imports and global vars
import pandas as pd
wordList = []
#opening the file
file = open("/home/jamie/Documents/Prototype/valid-wordle-words.txt","r")
words = file.readlines()
TOTAL_WORDS = len(words)
print(TOTAL_WORDS)

#strips the word file list of all non alpha numeric and assignes it to a list
def generateWords():
    fiveLetters = []

    for i in words:
        fiveLetters.append(i.strip())

    return fiveLetters

#finds frequency of letters in the dataset, returns a dataframe with each
#letter with percents of frequency of each letter
def findScores():
    letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 
               'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 
               's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
    scores = []
    for i in range(5):
      frequency = []
      
      for i in letters:
          frequency.append(0)
      scores.append(dict(zip(letters, frequency)))

    for i in range(5):
        for word in wordList:
          scores[i][word[i]] +=1
        for j in scores[i]:
          #turns it into a percent
          scores[i][j] = scores[i][j]/len(wordList)
    
    df = pd.DataFrame({
    'letters': letters,
    'letter1': list(scores[0].values()),
    'letter2': list(scores[1].values()),
    'letter3': list(scores[2].values()),
    'letter4': list(scores[3].values()),
    'letter5': list(scores[4].values())
})

    return df.set_index('letters')



#finds the higest scoring words based on frequency, returns the average percent
#frequency and adds a penalty to words with duplicate letters
#scores are divided by number of duplicates
#times the duplicate penalty returns a sorted dictionary of the best scoring
#words, words with no duplicates are not touched

def getWordScores(frequencyData,duplicatePenalty):
    timer = time.time()
    scoredf = frequencyData
    letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 
               'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 
               's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
    #gets the base score from the list of words
    scores = []
    for word in wordList:
        score = 0
        pos = 1
        for letter in word:
            index = 0
            while letter != letters[index]:
                index +=1
            score += scoredf['letter'+str(pos)][index]
            pos+=1
        scores.append(score/len(word))
        
    #penalises duplicates
    index = 0
    for word in wordList:
        dups = 0

        for i in range(5):
            for j in range(5):
                if i != j:
                    if word[i] == word[j]:
                        dups +=1
        if dups != 0:
          
          reduction = (dups*duplicatePenalty)
          scores[index] = scores[index] / reduction
        index +=1
    wordScores = dict(zip(wordList, scores))
    wordScores = sorted(wordScores.items(), key=lambda x: x[1], reverse=True)
    return wordScores



#returns a list of output for automatic training
def returnColors(word, answer):
  colors = [1,1,1,1,1]

  matches = []

  for i in range(len(word)):
    l = word[i]
    flg = False
    for j in range(len(word)):
      if answer[j] == l and colors[i] != 2:
        flg = True
        matches.append(l)

    if(flg != True):
      colors[i] = 0
  
  for i in range(len(word)):
    if word[i] == answer[i]:
      colors[i] = 2
  #finding matches
  
  

  return colors

#eliminates words from word list that are not possible
#guess is the word guessed, color is its colors, wordsLeft is the
#list of all un eliminated words, returns a list of words
def pruneList(initList,guess, colors):
  toRemove = []
  for word in initList:
    remove = False
    #eliminates greens on the same letter and yellows on the same letter
    for i in range(5):
      #removes green letters that are not the same position
      if(colors[i] == 2):
        if word[i] != guess[i]:
          
          remove = True
          break
      #removes yellow letters that are the same position (yellows must be different)
      if(colors[i] == 1):
        if(word[i] == guess[i]):
          remove = True
          break
          
          

    #removes word based on black letters
    if remove == False:
      
      for i in range(5):
        if(colors[i] == 0):
          for j in range(5):
            #if the black letter exists in the word delete it
           
            if(word[j] == guess[i]):
              
              remove = True
              break

            
    
    if remove == False:
      yellows = []
      for i in range(5):
        if colors[i] == 1:
          yellows.append(guess[i])
      #finds words containing yellow letters (accoutns for duplicates)
      #same letter yellows already removed
      if(len(yellows )> 0):
          yellowLetters = []
          for letter in yellows:
            yellowLetters.append(letter)
          #has a list of yellow letters, removes a letter from the yellow letter
          #list if it matches, if all are removed the letter is valid
          #takes care of duplicates due to wordle rules (1 yellow 1 black on dups
          #mean it has one of the letter, 2 yellow on dups mean it has 2)
          for i in word:
            for j in yellowLetters:
              if i == j:
                yellowLetters.remove(i)
          if(len(yellowLetters) != 0):
            remove = True
    if remove != True:
      toRemove.append(word)
  return toRemove

wordList = generateWords()
print(findScores())

turn = 1
topWords = 25
topLet = 10
width = 13
wordList = generateWords()
totalWords = len(generateWords())
colors = []
labelLen = []
letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 
               'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 
               's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
won = False
while(won == False or turn > 6):
  if(turn != 1):
    input("Press Enter for round "+str(turn))
  frequencies = findScores()
  best = getWordScores(frequencies,1)
  if(len(wordList) >= topWords):
    print("Most frequent of each letters")
    TopLtrs = []
    for i in range(5):
      letr = []
      temp =list( frequencies["letter"+str(i+1)])
      
      for j in range(topLet):
        if(len(temp)> 0):
          r = max(temp)
          letr.append('{: <{}}'.format("|"+str(letters[temp.index(r)].upper()+" = ")+str(round(r*100,2))+"%", width))
         
          temp.remove(r)


      TopLtrs.append(letr)

      
    df = pd.DataFrame()
    for i in range(5):
      df['{: <{}}'.format('|Letter: '+str(i+1),width)] = TopLtrs[i]
      
    print(df.reset_index())
    
    print("here are the top",topWords,"words based on average letter frequency")

    for i in range(topWords):
      percent = best[i][1]
      percent = percent * 100
      percent = round(percent,2)
      print("["+'{: <{}}'.format(str(i+1),3)+"] " +'{: <{}}'.format(best[i][0],5)+" : "+'{: <{}}'.format(str(percent),4) + "%")
    print("Round:"+str(turn)+": What word did you use?")
    guess = input()
  else:
    print("Most frequent of each letters")
    TopLtrs = []
    for i in range(5):
      letr = []
      temp =list( frequencies["letter"+str(i+1)])
      
      for j in range(topLet):
        if(len(temp)> 0):
          r = max(temp)
          letr.append('{: <{}}'.format("|"+str(letters[temp.index(r)].upper()+" = ")+str(round(r*100,2))+"%", width*5))
         
          temp.remove(r)


      TopLtrs.append(letr)

      
    df = pd.DataFrame()
    for i in range(5):
      df['{: <{}}'.format('|Letter: '+str(i+1),width)] = TopLtrs[i]
      
    print(df.style.hide_index())
    print("")
    print("best of the",len(wordList),"words left based on frequency")
    for i in range(len(wordList)):
      if i % 3 == 0:
          print("")
      percent = best[i][1]
      percent = percent * 100
      percent = round(percent,2)
      
      print('{: <{}}'.format("["+str(i)+"]:"+ best[i][0]+ " | score:" + str(percent) + "%",width),end="     ")
    guess = input("Round:"+str(turn)+" : what word did you use?: ")

    
  print("\n Now enter the color of each letter using spaces to seperate each letter")
  print("[⬛=0] [🟨=1] [🟩=2]" )
  a = ""
  b = ""
  confirm = False
  while(confirm == False):
    for i in guess:
      a=a+'{: <{}}'.format("["+str(i)+"]",3)
    
    colors = list(map(int,input("").strip().split()))[:5]
    for color in colors:
      if color == 0:
        b=b+"⬛"
      if color == 1:
        b=b+"🟨"
      if color == 2:
        b=b+"🟩"
    
    print('{: <{}}'.format(a,width))
    print('{: <{}}'.format(b,width))

    ans = input("Are these colors correct y/n?")
    while ans != "y" and ans != "n" :
      print(a)
      print(b)
      ans = input("Are these colors correct y/n?")
    if(ans == "y"):
      confirm = True


  before = len(wordList)
  print(guess,colors)
  wordList = pruneList(wordList,guess,colors)
  dif = before-len(wordList)
  print(str(round(dif*100/totalWords,2))+"%", "of the words words eliminated", len(wordList),"words remain")
  print(str(round(before*100/totalWords,2))+"%  ---->  "+str(round(len(wordList)*100/totalWords,2))+"%")
  colors = []

  if(len(wordList) == 1):
    won = True
  turn +=1

if(turn-1 > 6):
  print("Very unlucky!!!!!")
  quit()
else:
  print("The answer is: ",wordList[0])
  print("You got it in",turn-1,"tries!")
  quit()
